export const recoveryWords = [
  'amber', 'anchor', 'apple', 'april', 'artist', 'atom', 'autumn', 'bamboo',
  'banner', 'beacon', 'beach', 'berry', 'bicycle', 'bird', 'blossom', 'boat',
  'breeze', 'brook', 'cabin', 'cactus', 'candle', 'canyon', 'captain', 'carpet',
  'castle', 'cedar', 'cherry', 'circle', 'cloud', 'clover', 'coast', 'comet',
  'copper', 'coral', 'cotton', 'crystal', 'dawn', 'delta', 'desert', 'dolphin',
  'dragon', 'dream', 'drift', 'dune', 'eagle', 'earth', 'ember', 'engine',
  'falcon', 'feather', 'field', 'firefly', 'forest', 'fossil', 'fountain', 'galaxy',
  'garden', 'glacier', 'globe', 'gold', 'granite', 'grove', 'harbor', 'harmony',
  'hazel', 'helmet', 'horizon', 'island', 'jacket', 'jasmine', 'journey', 'jungle',
  'keeper', 'kernel', 'kingdom', 'ladder', 'lagoon', 'lantern', 'laurel', 'legend',
  'lemon', 'linen', 'lotus', 'marble', 'meadow', 'meteor', 'mint', 'mirror',
  'monsoon', 'morning', 'mountain', 'museum', 'nebula', 'needle', 'noble', 'north',
  'oak', 'oasis', 'ocean', 'olive', 'orbit', 'orchid', 'otter', 'paddle',
  'paper', 'pearl', 'pepper', 'phoenix', 'piano', 'pine', 'planet', 'plaza',
  'pocket', 'prairie', 'prism', 'puzzle', 'quartz', 'quest', 'quiet', 'raven',
  'reef', 'river', 'rocket', 'saddle', 'saffron', 'sail', 'scarlet', 'shadow',
  'signal', 'silver', 'sky', 'solar', 'sparrow', 'spring', 'stone', 'summit',
  'sunset', 'talon', 'temple', 'thunder', 'timber', 'torch', 'tower', 'trail',
  'travel', 'tulip', 'valley', 'velvet', 'venture', 'violet', 'voyage', 'water',
  'whisper', 'willow', 'window', 'winter', 'wood', 'zephyr',
];
